### ISSUE TITLE
Users can follow themselves

### ISSUE THREAD

**Issue by aseerkt** [siddharthroy12/insta-clone#1] opened 2021-06-07 10:22 UTC
Remove follow button from the logged in user profile page.

**Comment by siddharthroy12** [comment] 2021-06-07 10:28
It's not a bug it's a feature lol

I'll fix it later

**Comment by siddharthroy12** [comment] 2021-06-08 03:47
Fixed in commit: 295081088dec45f17668c006689ef6545e8dd796

**Closed by siddharthroy12** 2021-06-08 03:47 UTC
